language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y xmldiff
  - git clone https://github.com/proycon/pynlpl.git
  - cd pynlpl
  - pip install -r requirements.txt
  - sudo setup.py install
  - cd ..
install: 
  - python setup.py install
script:  
  - cd test && test.sh
